### ISSUE TITLE
blue is incompatible with flake8 v5

### ISSUE THREAD

**Issue by RobertCraigie** [grantjenks/blue#78]
[Flake8 v5](https://flake8.pycqa.org/en/latest/release-notes/5.0.0.html) was just released earlier today. Unfortunately this breaks `blue` as it now crashes with this error:

```
Traceback (most recent call last):
  File "/tmp/tox/prisma-client-py/lint/lib/python3.9/site-packages/blue/__init__.py", line 397, in <module>
    BaseConfigParser = flake8_config.ConfigParser              # flake8 v4
AttributeError: module 'flake8.options.config' has no attribute 'ConfigParser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tox/prisma-client-py/lint/bin/blue", line 5, in <module>
    from blue import main
  File "/tmp/tox/prisma-client-py/lint/lib/python3.9/site-packages/blue/__init__.py", line 399, in <module>
    BaseConfigParser = flake8_config.MergedConfigParser        # flake8 v3
AttributeError: module 'flake8.options.config' has no attribute 'MergedConfigParser'
```

Constraining the flake8 dependency to v4 fixes the error.

**Comment by krcb197** [comment]
I have been able to work around this problem by adding a dependency in setup.py for my project on flake8<=4.0.1, the same workaround can be done in a requirements.txt

**Comment by warsaw** [comment]
Okay, this does look like a trickier incompatibility to resolve.  It looks like `flake8` didn't just change the name of the config class, they changed the way they parse the configs.  So I think for now, a quick fix is the pin in #79 but we should leave this issue open pending a proper fix.

**Comment by danigm** [comment]
I think this patch will fix the issue

[flake8-v5-compatibility.patch.txt](https://github.com/grantjenks/blue/files/9598516/flake8-v5-compatibility.patch.txt)

**Comment by sshishov** [comment]
Could we guys fix the issue? The issue is open for half of the year. Flake8 has already `v6` btw

**Comment by xmnlab** [comment]
hey everyone, any plan for supporting flake8 v5 and v6?

**Comment by sshishov** [comment]
@xmnlab I guess we have to come up with pull request for this to support it. Otherwise the issue will be open for years...

**Comment by warsaw** [comment]
If you can, I'll review it.

**Comment by kaweantonio** [comment]
> If you can, I'll review it.

Hi, @warsaw, I opened PR #96 to fix this issue. Can you review it?
