### ISSUE TITLE
Unable to run Blue formatting

### ISSUE THREAD

**Issue by gturbyne** [grantjenks/blue#81]
Seems like I'm unable to get blue to run anymore...

I consistently get the following error:
`
Traceback (most recent call last):
  File "/Users/gturbyne/workspace/sonarqube-tools/build/sonarqube-tools/environments/satellites/codeQuality/bin/blue", line 5, in <module>
    from blue import main
  File "/Users/gturbyne/workspace/sonarqube-tools/build/sonarqube-tools/environments/satellites/codeQuality/lib/python3.7/site-packages/blue/__init__.py", line 10, in <module>
    import black
  File "/Users/gturbyne/workspace/sonarqube-tools/build/sonarqube-tools/environments/satellites/codeQuality/lib/python3.7/site-packages/black/__init__.py", line 371, in <module>
    ) -> None:
  File "/Users/gturbyne/workspace/sonarqube-tools/build/sonarqube-tools/environments/satellites/python/lib/python3.7/site-packages/click/decorators.py", line 170, in decorator
    _param_memo(f, OptionClass(param_decls, **attrs))
  File "/Users/gturbyne/workspace/sonarqube-tools/build/sonarqube-tools/environments/satellites/python/lib/python3.7/site-packages/click/core.py", line 1460, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'hidden'
DURATION: 0.51s
`

**Comment by grantjenks** [comment]
Which version of blue is getting used here? And can you share the CLI args?

**Comment by gturbyne** [comment]
Hmm, looks like gradle is pulling in version `0.7.0` by default. Here is the full command that was run when I invoked the task:
`'PYTHONDONTWRITEBYTECODE='1' PYTHONPATH='/Users/gturbyne/workspace/sonarqube-tools/build/sonarqube-tools/environments/venv/lib/python3.7/site-packages:/Users/gturbyne/workspace/sonarqube-tools/build/sonarqube-tools/environments/satellites/python/lib/python3.7/site-packages:/Users/gturbyne/workspace/sonarqube-tools/build/sonarqube-tools/environments/satellites/codeQuality/lib/python3.7/site-packages' /Users/gturbyne/workspace/sonarqube-tools/build/sonarqube-tools/environments/venv/bin/python /Users/gturbyne/workspace/sonarqube-tools/build/sonarqube-tools/environments/satellites/codeQuality/bin/blue --target-version py37 -l 120 /Users/gturbyne/workspace/sonarqube-tools/sonarqube-tools/src /Users/gturbyne/workspace/sonarqube-tools/sonarqube-tools/test'`

**Comment by warsaw** [comment]
@gturbyne If you're using flake8 v5, Python 3.10, or Python 3.11 you probably want to use the latest version 0.9.1.

**Comment by gturbyne** [comment]
Hey @warsaw, I tried pulling in the latest version by adding it to my `product-spec.json`, and saw that the correct version was added into my build dir, however I’m still getting the same error.
